# Generated by Django 6.0.4 on 2026-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_add_unique_pending_claim'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE items_item SET status='OPEN' WHERE status='CLAIMED';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=8),
        ),
    ]
